jobs:
  Build:
    name: Run Sonarqube
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Install JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '21'
    - continue-on-error: true
      name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-sonar
    - continue-on-error: true
      name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
        restore-keys: ${{ runner.os }}-gradle
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: Build and analyze
      run: ./gradlew build sonarqube --info -Dorg.gradle.jvmargs=-XX:MaxMetaspaceSize=512m
name: Sonarqube
on:
  repository_dispatch:
    types: trigger-ga___sonarqube.yml
